### ISSUE TITLE
Support OTP 18

### ISSUE THREAD

**Issue by chwevans** [seth/pooler#46]
Currently pooler.erl:209 uses erlang:now() to get the seconds component of time. This causes rebar to error out due to deprecation warnings. There are a few options to maintain backwards compatibility, one of which is to use http://www.erlang.org/doc/apps/erts/time_compat.erl. This exposes functions that use the OTP 18 new time functions if available and the old ones otherwise. Alternatively, you can not warn on deprecated functions in the rebar.config.

**Comment by sdebnath** [comment]
R18 deprecates erlang:now/0. Unfortunately, the new erlang:system_time or
the erlang:timestamp that is recommended is not available prior to R18. To
maintain a compatible codebase across both releases, os:timestamp/0 is the
way to go where monotonically increasing timestamp is not required.

PR #47

**Comment by juise** [comment]
Looks like outdated issue

**Comment by sdebnath** [comment]
Yes - #47 resolved the issue. @seth you can close this issue.

**Comment by seth** [comment]
Builds and tests pass on Erlang 18.
