### ISSUE TITLE
Build failure with OTP 18.1

### ISSUE THREAD

**Issue by building39** [seth/pooler#55]
mmartin@testcat:~/git/pooler$ make
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> pooler (get-deps)
Pulling rebar_lock_deps_plugin from {git,
                                     "git://github.com/seth/rebar_lock_deps_plugin.git",
                                     {branch,"master"}}
Cloning into 'rebar_lock_deps_plugin'...
Pulling edown from {git,"git://github.com/seth/edown.git",{branch,"master"}}
Cloning into 'edown'...
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> edown (get-deps)
WARN:  Missing plugins: [rebar_lock_deps_plugin]
WARN:  Missing plugins: [rebar_lock_deps_plugin]
==> rebar_lock_deps_plugin (compile)
Compiled src/rldp_util.erl
Compiled src/rldp_change_log.erl
Compiled src/rebar_lock_deps_plugin.erl
==> edown (compile)
Compiled src/edown_make.erl
Compiled src/edown_lib.erl
Compiled src/edown_xmerl.erl
/home/mmartin/git/pooler/deps/edown/src/edown_doclet.erl:116: field packages undefined in record doclet_gen
/home/mmartin/git/pooler/deps/edown/src/edown_doclet.erl:118: field filemap undefined in record doclet_gen
Compiling /home/mmartin/git/pooler/deps/edown/src/edown_doclet.erl failed:
ERROR: compile failed while processing /home/mmartin/git/pooler/deps/edown: rebar_abort
make: *** [compile] Error 1

**Comment by juise** [comment]
+1

**Comment by seth** [comment]
Master builds on Erlang 18 now. Thanks for the report.
