### ISSUE TITLE
pooler:take_member returns same PID all the time

### ISSUE THREAD

**Issue by szymon-wlodarczyk** [seth/pooler#56]
Hello,
I am using pooler application from tag 1.5.0
I use following pooler configuration:

```
{pooler, [
           {pools, [
                    [
                     {name, riak_pool},
                     {group, riak},
                     {max_count, 20},
                     {init_count, 10},
                     %% client_option() :: queue_if_disconnected |
                     %% {queue_if_disconnected, boolean()} |
                     %% {connect_timeout, pos_integer()} |
                     %%     auto_reconnect |
                     %% {auto_reconnect, boolean()}.
                     {start_mfa, {riakc_pb_socket, start_link, ["localhost", 8087,
                         [queue_if_disconnected, auto_reconnect]]}}
                    ]
                   ]
            }
           ]
  }
```

I run queries using this approach:

```
Pid = connect(),
... using Pid ...
close(Pid),
...
```
connect and close functions are below:

```
connect() ->
    Pid = pooler:take_member(riak_pool, 5000),
    lager:debug("Retrieved PID ~p from pooler", [Pid]),
    Pid.
```
```
close(Pid) ->
    lager:debug("Returning PID ~p to pooler", [Pid]),
    pooler:return_member(riak_pool, Pid, ok).
```

In other module which has application behaviour I run pooler:

```
application(pooler)
```

The problem is that, I retrieve same Pid all the time. 
I am sure that many processes in parallel are invoking connect and close methods but all the time same Pid is used.

Is there a bug in this version or am I doing something in a wrong way?

Regards,
Szymon Wlodarczyk

**Comment by sata** [comment]
I don't see anything obviously wrong, could you please provide the full test code so I can test locally?

**Comment by szymon-wlodarczyk** [comment]
Unfortunately I think that wont be possible to provide whole code, because those code snippets I provided are part of bigger erlang application which I develop.
I didn't try to do downgrade of pooler, I can try that.
I didn't mention that earlier but I am using E16B03. This version is supported by 1.5.0?

**Comment by sata** [comment]
Shouldn't take long to create a small example project with the interesting pieces of code. Essentially a 10 minute job?

**Comment by szymon-wlodarczyk** [comment]
Sorry for so looong answer.
I am not that good with erlang :(
I created simple app which shows how I use pooler in my application.

[src.zip](https://github.com/seth/pooler/files/210044/src.zip)

Thanks in advance for any help on this.
Szymon

**Comment by szymon-wlodarczyk** [comment]
I know that my problem won't be probable reproducible here.
This application is similar to one app I have in my application, which is resposible for connection with riak.
When I run performance tests against my app I can see that only one PID is used all the time.
Probably by adding simple wait or some loop to ping() will allow us to reproduce this issue.

**Comment by szymon-wlodarczyk** [comment]
Hello,
Anyone had chance to look into this?
Szymon

**Comment by szymon-wlodarczyk** [comment]
@seth do you have any idea what I am doing wrong here?

**Comment by seth** [comment]
Are you encountering a problem where multiple processes are using the same pid at the same time? If so, that's for sure a bug (and a very serious one).

Pooler is designed to vend the most recently used pool member. So if you take/return in a loop, you'll always get the same member. Is it possible that you are seeing this behavior and not experiencing a problem as a result of it?

**Comment by szymon-wlodarczyk** [comment]
I don't know if many processes use same pid for DB queries.
We did some performance testing of our component written in erlang with usage of pooler.
Test firstly sends 50k messages to the messaging queue. When it is done then we connect our erlang app which retrieves messages from queue.
One process consumes messages from queue and runs new process for each retrieved message in order to handle it (run DB query and send response), so I am pretty sure that we have multiple processes using pool.
I just came up with an idea - I can add timer:sleep() in queries and check out if new processes are used from pool. Maybe queries are so fast that only one process from pool is used?
But as far I remember DB has a lot of data (not same amount as in production but queries should be long enough in order to expose this issue).

**Comment by szymon-wlodarczyk** [comment]
Hello,
Everything is working as expected. I made a terrible mistake in code. 
In different place, before DB query execution, I had serial execution of code and that is why always same PID from pool was used.
You can close the issue.
Thanks for your time guys.
